sudo: required
services:
  - docker

before_install:
  - docker build -t baterfly85/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run baterfly85/react-test npm test -- --coverage

after_success:
  - docker build -t baterfly85/multi-client
  - docker build -t baterfly85/multi-nginx ./multi-nginx
  - docker build -t baterfly85/multi-server ./server
  - docker build -t baterfly85/multi-worker ./worker
  # Log in to the docker client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push baterfly85/multi-client
  - docker push baterfly85/multi-nginx
  - docker push baterfly85/multi-server
  - docker push baterfly85/multi-worker